Repository NVIDIA-Merlin/dataloader, pull requests merged in 2022-12, with the labels that each got.

#78 Adds context manager
  merlin/dataloader/loader_base.py
  tests/unit/dataloader/test_jax_dataloader.py
  tests/unit/dataloader/test_tf_dataloader.py
  tests/unit/dataloader/test_torch_dataloader.py
Labels: enhancement

#79 Revert to using Keras Sequence for TensorFlow Loader
  merlin/dataloader/loader_base.py
  merlin/dataloader/tensorflow.py
  tests/unit/dataloader/test_tf_dataloader.py
Labels: bug

#83 Remove echo from tox.ini
  tox.ini
Labels: ci, chore

#63 Update pytorch getting started test and setup examples tests to run in CI
  ci/test_unit.sh
  examples/01a-Getting-started-Tensorflow.ipynb
  examples/01b-Getting-started-Pytorch.ipynb
  tests/examples/test_getting_started_pytorch.py
  tox.ini
Labels: ci

#86 Add schema setter to enable changing loader features on Loader instance
  merlin/dataloader/loader_base.py
  merlin/dataloader/ops/embeddings/embedding_op.py
  tests/unit/dataloader/test_tf_dataloader.py
  tests/unit/dataloader/test_tf_embeddings.py
Labels: enhancement

#87 Check Input Schema setter with list feature
  merlin/dataloader/loader_base.py
  tests/unit/dataloader/test_tf_dataloader.py
Labels: bug

#88 activate gha runner for gpu-ci
  .github/workflows/gpu-ci.yml
Labels: ci, chore

#89 Use tf.function for list column operations
  tests/unit/dataloader/test_tf_dataloader.py
Labels: bug, ci
