Repository NVIDIA-Merlin/dataloader, pull requests merged in 2022-11, with the labels that each got.

#42 add tox ini as entrypoint for tests in cpu gha
  .github/workflows/cpu-ci.yml
  .pylintrc
  requirements/docs.txt
  tox.ini
Labels: ci, chore

#41 Dl transforms
  merlin/loader/loader_base.py
  merlin/loader/ops/__init__.py
  merlin/loader/ops/embeddings/__init__.py
  merlin/loader/ops/embeddings/embedding_op.py
  merlin/loader/ops/embeddings/tf_embedding_op.py
  merlin/loader/ops/embeddings/torch_embedding_op.py
  merlin/loader/tensorflow.py
  merlin/loader/torch.py
  requirements/base.txt
  requirements/dev.txt
  tests/conftest.py
  tests/unit/loader/test_tf_embeddings.py
  tests/unit/loader/test_torch_embeddings.py
  tox.ini
Labels: enhancement

#45 Put values and offsets on the same device on gpu
  merlin/loader/torch.py
  tox.ini
Labels: bug

#43 docs: Add basic SEO configuration
  docs/source/README.md
  docs/source/conf.py
Labels: documentation, skip-changelog

#53 Use value_count max only for sparse max instead of min == max
  merlin/loader/loader_base.py
  tests/unit/loader/test_tf_dataloader.py
  tests/unit/loader/test_torch_dataloader.py
Labels: enhancement

#55 Add lint workflow using pre-commit
  .github/workflows/cpu-ci.yml
  .github/workflows/lint.yml
  .pre-commit-config.yaml
  .pylintrc
  merlin/loader/loader_base.py
  merlin/loader/torch.py
  merlin/loader/utils/tf/tf_trainer.py
  requirements/dev.txt
  tests/unit/loader/test_tf_dataloader.py
  tox.ini
  versioneer.py
Labels: ci

#59 add in mechanism for creating release drafts
  .github/release-drafter.yml
  .github/workflows/release-drafter.yaml
Labels: documentation, ci, chore

#47 [WIP] add examples
  examples/01a-Getting-started-Tensorflow.ipynb
  examples/01b-Getting-started-Pytorch.ipynb
  examples/README.md
  requirements/dev.txt
  tests/examples/test_getting_started_pytorch.py
  tests/examples/test_getting_started_tensorflow.py
Labels: examples

#52 chore: Reduce docs size and update build actions
  .github/workflows/cpu-ci.yml
  .github/workflows/docs-preview-pr.yaml
  .github/workflows/docs-remove-stale-reviews.yaml
  .github/workflows/docs-sched-rebuild.yaml
  docs/source/conf.py
Labels: chore, skip-changelog

#61 Add Min Python Version and language classifiers
  requirements/base.txt
  setup.py
Labels: chore

#71 fix naming
  examples/01b-Getting-started-Pytorch.ipynb
Labels: examples

#70 Add common files to .gitignore
  .gitignore
Labels: chore

#68 Add workflow to run tests with different TensorFlow versions
  .github/workflows/jax.yaml
  .github/workflows/tensorflow.yml
  .github/workflows/torch.yaml
  requirements/jax.txt
  setup.py
  tests/examples/test_getting_started_pytorch.py
  tests/examples/test_getting_started_tensorflow.py
  tests/unit/dataloader/test_jax_dataloader.py
  tests/unit/dataloader/test_tf_dataloader.py
  tests/unit/dataloader/test_tf_embeddings.py
  tests/unit/dataloader/test_torch_dataloader.py
  tests/unit/dataloader/test_torch_embeddings.py
  tox.ini
Labels: ci

#65 Update TensorFlow Loader to run as iterator instead of Keras Sequence
  merlin/dataloader/loader_base.py
  merlin/dataloader/tensorflow.py
  tests/unit/dataloader/test_tf_dataloader.py
  tests/unit/dataloader/test_torch_dataloader.py
Labels: bug

#73 Add Prettier formatter for YAML and Markdown
  .github/workflows/lint.yml
  .pre-commit-config.yaml
  .prettierignore
  .yamllint.yaml
  README.md
Labels: chore

#77 Add `peek` method to get first batch without advancing iterator
  examples/01a-Getting-started-Tensorflow.ipynb
  examples/01b-Getting-started-Pytorch.ipynb
  merlin/dataloader/loader_base.py
  tests/unit/dataloader/test_jax_dataloader.py
  tests/unit/dataloader/test_tf_dataloader.py
  tests/unit/dataloader/test_torch_dataloader.py
Labels: enhancement
