Repository NVIDIA-Merlin/dataloader, pull requests merged in 2023-05, with the labels that each got.

#144 Remove use of deprecated numpy aliases of builtin types
  tests/unit/dataloader/test_torch_dataloader.py
Labels: chore

#142 Add workflows to check base branch and set stable branch
  .github/workflows/check-base-branch.yaml
  .github/workflows/set-stable-branch.yaml
Labels: ci

#143 Update tag pattern in GitHub Workflows
  .github/workflows/cpu-ci.yml
  .github/workflows/cpu-packages.yml
  .github/workflows/docs-sched-rebuild.yaml
  .github/workflows/gpu-ci.yml
  .github/workflows/jax.yaml
  .github/workflows/models.yml
  .github/workflows/nvtabular.yml
  .github/workflows/release-drafter.yaml
  .github/workflows/systems.yml
  .github/workflows/tensorflow.yml
  .github/workflows/torch.yaml
  .github/workflows/transformers4rec.yml
Labels: ci

#118 Update checks of HAS_GPU in tests to handle case where cudf is not installed
  tests/unit/dataloader/test_tf_dataloader.py
  tests/unit/dataloader/test_torch_dataloader.py
Labels: chore

#146 Adjust tag propagation in `EmbeddingOperator`
  merlin/dataloader/ops/embeddings.py
  tests/unit/dataloader/test_embeddings.py
Labels: bug

#148 Use Dictionary lookup for supplied IDs to Embedding Operator
  merlin/dataloader/ops/embeddings.py
  tests/unit/dataloader/test_embeddings.py
Labels: enhancement
