Repository NVIDIA-Merlin/dataloader, pull requests merged in 2023-04, with the labels that each got.

#122 remove numpy tensorflow conversion logic in tf dataloader
  merlin/dataloader/tensorflow.py
Labels: bug, chore

#123 Remove reset of dataloader in len method of `ArrayLoader`
  merlin/dataloader/array.py
  merlin/dataloader/tensorflow.py
  tests/unit/dataloader/test_torch_dataloader.py
Labels: chore

#119 imports for GPU packages from compat
  merlin/dataloader/loader_base.py
  merlin/dataloader/utils/tf/tf_trainer.py
  tests/conftest.py
Labels: enhancement, ci, chore

#121 Array loaderbase merge
  merlin/dataloader/array.py
  merlin/dataloader/jax.py
  merlin/dataloader/loader_base.py
  merlin/dataloader/tensorflow.py
  merlin/dataloader/torch.py
  tests/unit/dataloader/test_array_to_tensorflow.py
  tests/unit/dataloader/test_array_to_torch.py
  tests/unit/dataloader/test_embeddings.py
Labels: chore

#126 Add downstream repo tests
  .github/workflows/models.yml
  .github/workflows/nvtabular.yml
  .github/workflows/systems.yml
  .github/workflows/transformers4rec.yml
  tox.ini
Labels: enhancement, ci

#127 fixing imports for tf and torch in dataloader
  merlin/dataloader/tensorflow.py
  merlin/dataloader/torch.py
  tests/unit/dataloader/test_array_to_tensorflow.py
  tests/unit/dataloader/test_array_to_torch.py
Labels: enhancement, chore

#129 Apply map function when peeking in tensorflow
  merlin/dataloader/tensorflow.py
  tests/unit/dataloader/test_tf_dataloader.py
Labels: bug

#125 Adding Pad op
  merlin/dataloader/loader_base.py
  merlin/dataloader/ops/padding.py
  tests/unit/dataloader/test_array_dataloader.py
  tests/unit/dataloader/test_padding.py
Labels: enhancement, chore

#132 Set device for torch tensors with gpu > 1
  merlin/dataloader/loader_base.py
  merlin/dataloader/torch.py
Labels: bug

#134 Revert "Set device for torch tensors with gpu > 1 (#132)"
  merlin/dataloader/loader_base.py
  merlin/dataloader/torch.py
Labels: bug, chore

#137 Enable transforms to work when targets are output from dataloader
  merlin/dataloader/loader_base.py
  tests/unit/dataloader/test_embeddings.py
Labels: chore

#138 Consolidate Embedding Operator and add offsets to embeddings
  merlin/dataloader/ops/embeddings.py
  tests/unit/dataloader/test_embeddings.py
Labels: bug

#139 fix array dl tests gpu vs cpu
  tests/unit/dataloader/test_array_dataloader.py
Labels: bug, ci

#140 Update requirements for Merlin packages to minimum version of 23.04
  requirements/base.txt
Labels: chore
