Repository NVIDIA-Merlin/dataloader, pull requests merged in 2023-06, with the labels that each got.

#152 Install dependencies in downstream tests
  tox.ini
Labels: ci

#149 adding ops-bot yaml file
  .github/ops-bot.yaml
Labels: ci

#141 update workflow on which docs pr preview depends
  .github/workflows/docs-preview-pr.yaml
Labels: chore

#154 Update merlin-core version specifier to match current release
  requirements/base.txt
Labels: chore, dependencies, skip-base-branch-check
