Repository NVIDIA-Merlin/dataloader, pull requests merged in 2023-01, with the labels that each got.

#90 add `map` to torch Loader
  merlin/dataloader/torch.py
  tests/unit/dataloader/test_torch_dataloader.py
Labels: enhancement

#92 Add a legal statement to the notebooks
  examples/01a-Getting-started-Tensorflow.ipynb
  examples/01b-Getting-started-Pytorch.ipynb
Labels: documentation, skip-changelog

#93 Split CPU tests and building packages into separate Github Actions
  .github/workflows/cpu-ci.yml
  .github/workflows/cpu-packages.yml
Labels: ci, chore

#81 add example for running on multiple GPUs using Horovod
  examples/02-Multi-GPU-Tensorflow-with-Horovod.ipynb
  tests/examples/test_multi_GPU_with_horovod_and_tensorflow.py
Labels: documentation, examples

#94 Update docs support info in README
  docs/README.md
Labels: chore, skip-changelog
