Repository NVIDIA-Merlin/dataloader, pull requests merged in 2023-03, with the labels that each got.

#109 Correct cpu-packages config
  .github/workflows/cpu-packages.yml
Labels: ci

#110 Apply the `EMBEDDING` tag to the output of the embedding operators
  merlin/dataloader/ops/embeddings/embedding_op.py
  tests/unit/dataloader/test_tf_embeddings.py
  tests/unit/dataloader/test_torch_embeddings.py
Labels: enhancement

#103 Remove sparse tensor output type for list features
  merlin/dataloader/loader_base.py
  merlin/dataloader/tensorflow.py
  merlin/dataloader/torch.py
  tests/unit/dataloader/test_tf_dataloader.py
  tests/unit/dataloader/test_torch_dataloader.py
Labels: enhancement

#113 Put row lengths on the same device on gpu
  merlin/dataloader/torch.py
  tests/unit/dataloader/test_torch_dataloader.py
Labels: bug

#114 Update default value of cpu to None in dataset fixture
  tests/conftest.py
Labels: chore

#115 Change row lengths unit tests to use cpu and single gpu
  tests/unit/dataloader/test_torch_dataloader.py
Labels: bug, ci, chore

#116 Remove reshape to speed up loading of scalar features in TensorFlow
  merlin/dataloader/jax.py
  merlin/dataloader/loader_base.py
  merlin/dataloader/tensorflow.py
  merlin/dataloader/torch.py
Labels: chore

#120 replace dictarray for tensortable in transforms functionality
  merlin/dataloader/loader_base.py
  merlin/dataloader/ops/embeddings/embedding_op.py
  merlin/dataloader/ops/embeddings/tf_embedding_op.py
  merlin/dataloader/ops/embeddings/torch_embedding_op.py
  tests/unit/dataloader/test_tf_embeddings.py
  tests/unit/dataloader/test_torch_embeddings.py
Labels: chore

#111 adding array version of dataloader
  merlin/dataloader/array.py
  merlin/dataloader/jax.py
  merlin/dataloader/loader_base.py
  merlin/dataloader/ops/embeddings.py
  merlin/dataloader/ops/embeddings/__init__.py
  merlin/dataloader/ops/embeddings/tf_embedding_op.py
  merlin/dataloader/ops/embeddings/torch_embedding_op.py
  merlin/dataloader/tensorflow.py
  merlin/dataloader/torch.py
  tests/unit/dataloader/test_array_dataloader.py
  tests/unit/dataloader/test_array_to_tensorflow.py
  tests/unit/dataloader/test_array_to_torch.py
  tests/unit/dataloader/test_embeddings.py
  tests/unit/dataloader/test_tf_dataloader.py
  tests/unit/dataloader/test_tf_embeddings.py
  tests/unit/dataloader/test_torch_dataloader.py
Labels: enhancement
