Repository NVIDIA-Merlin/dataloader, pull requests merged in 2023-02, with the labels that each got.

#49 Add Jenkinsfile
  ci/pr.gpu.Jenkinsfile
Labels: ci, chore, gpuCI-test-this

#98 fix gpu visibility on docker
  tox.ini
Labels: ci, chore

#99 Replace `nnzs` with `row_lengths` for clarity
  .pre-commit-config.yaml
  merlin/dataloader/loader_base.py
  merlin/dataloader/tensorflow.py
  merlin/dataloader/utils/tf/tf_trainer.py
  tests/unit/dataloader/test_tf_dataloader.py
Labels: chore

#102 docs: Rebuild docs on push
  .github/workflows/docs-sched-rebuild.yaml
Labels: chore, skip-changelog

#107 Restore support for passing `device` in CPU-only environment
  merlin/dataloader/loader_base.py
  tests/unit/dataloader/test_tf_dataloader.py
Labels: chore
